### ISSUE TITLE
buildLoaderConfig halts if path does not exist

### ISSUE THREAD

**Issue by christophersmith262** [basaltinc/twig-tools#5]
If one of the paths under any namespace in does not exist and recursive detection is enabled, none of the twig namespaces will be registered.

For example if we have:
```
"my-first-namespace": {
  "recursive": true,
  "paths": [
    "/this-doesn't-exist",
  ]
},
"my-second-namespace": {
  "recursive": true,
  "paths": [
    "/this-_does_-exist",
  ]
}
```

If this twig-namespaces file is parsed, no twig namespaces are registered, even though there is only an issue with "my-first-namespace"

This hasn't come up as a problem yet, but it popped up when messing around with bolt_connect.

I believe the path should be ignored if it doesn't exist instead of blowing up every proceeding namespace.

@charginghawk @EvanLovely

**Comment by EvanLovely** [comment]
Good catch! We should get this fixed. Have any thoughts on the solution? /cc @sghoweri

**Comment by christophersmith262** [comment]
@EvanLovely I submitted a PR here:
https://github.com/basaltinc/twig-tools/pull/6

It just skips the path if it does not exist instead of trying to recurse down it.

**Comment by EvanLovely** [comment]
Thank you! Released in https://github.com/basaltinc/twig-tools/releases/tag/v1.4.3
