### ISSUE TITLE
Repo went missing?

### ISSUE THREAD

**Issue by stephencapellic** [basaltinc/twig-tools#8]
Hello,

We have a couple of websites that are using an old version of PatterLab. Our builds stopped working last week due to this repository not being available. 

Can you shed some light on what happened? What are the plans for this repository moving forward? Should we be using a different repository?

Thank you in advance, I appreciate your contributions to the open source community.

- Stephen

**Comment by greylabel** [comment]
We were cleaning up some older repos that are no longer actively maintained and are quite out of date. This one was changed to a private archive. We plan to make it a public archive instead and do not plan any future updates.

related: https://github.com/EvanLovely/plugin-twig-namespaces/issues/7
